### ISSUE TITLE
Sent emails still labeled as In Queue

### ISSUE THREAD

**Issue by mmuldoon** [easydigitaldownloads/fes-product-updates#10]
So I thought the was fixed, but it looks like it maybe isn't, just had a fluke on that worked. Sent emails are still being labeled as In Queue after they are sent in the Product Updates Panel.
![error](http://i.imgur.com/3eL2W71.png)

**Comment by pippinsplugins** [comment]
Hmm, I just sent out an update from easydigitaldownloads.com and this did not happen.

Does it happen on your staging site too?

**Comment by mmuldoon** [comment]
Looks good now Pip, until it rears it's head again. 
Thanks
