### ISSUE TITLE
Standardize Footer

### ISSUE THREAD

**Issue by mmuldoon** [easydigitaldownloads/fes-product-updates#6]
Copyright © 2015 CG Cookie, All rights reserved.
You are receiving this email because you made a purchase from the Blender Market.
If you don't wish to receive these kinds of emails, click here to unsubscribe.

**Comment by pippinsplugins** [comment]
I've added a setting to the Emails tab that lets you defined the default content.
![screen shot 2015-02-05 at 1 51 05 pm](https://cloud.githubusercontent.com/assets/1034109/6067963/188fbba2-ad3e-11e4-857d-eb79a9d7d7e0.png)
