### ISSUE TITLE
Notification email to admins about new product email

### ISSUE THREAD

**Issue by mmuldoon** [easydigitaldownloads/fes-product-updates#8]
Would it be possible for site admins to be notified when a new product update email is submitted?

**Comment by pippinsplugins** [comment]
It does that already, you just need to add your email in Downloads > Settings > Emails: https://cloudup.com/cr-laN-jgB8

**Comment by mmuldoon** [comment]
Sorry Pip, looks like this is a bug we've been fighting since the site started that doesn't send out emails for sales either. So that's why we didn't get any. 
Cheers,
